### ISSUE TITLE
ご相談事項：1.スライド登録機能について

### ISSUE THREAD

**Issue by tsukamotomizuho** [tsukamotomizuho/presentation#1]
★ご相談、質問事項：3件★

1)スライドをajax処理で送信する方法がわかりません
・質問
　良いやり方or参考ページをご存じでしたらご教授ください。
　回答ページをうまく検索できませんでした。すみません。

・以下つまったところです
⇒スライド画像が入ったファイルをinput要素で取得（webkitdirectoryのオプションを使用）
⇒スライド画像が入ったファイルの値？をjavascriptで受け取る方法がわかりません
　そのため、ajaxに渡す値を作ることができず、断念。

2)DBに格納するスライド情報について
・質問
　DBに格納するスライド情報は画像情報(データURL)にすべきでしょうか？

⇒現在は以下の方法でスライドを保存、表示させています。
　1)画像ファイル辞自体は/uploadフォルダに保存しています。（『①スライドを画面に表示』ボタンで実行）
  2)現在はスライドの画像名のみDBに保存しています。(『②スライドをDBに登録』ボタンで実行)

3)スライドのアップロード方法について
・相談
　現手法（スライドを画像としてUL）だとアニメーション機能が使えません。
  この部分を解消してくれそうなAPI(Google Slides API)があり、気になっています。
 　・アニメーションを再現する方法をもう少し探ってみるべきでしょうか？
 　・まだミニマム要素（音声登録機能等の実装）が終わっていないので、
 　　そちらを先に進めるべきでしょうか？
　　
・現手法：初回メンタリングで話していた通り、以下の手法を取りました。
⇒スライド画像が入ったファイルをアップロード
⇒slick.js(API)で表示

・気になるAPI：Google Slides API
　https://qiita.com/howdy39/items/be30170f8722c6837ea5
・Google Slides
　https://www.google.com/intl/ja_jp/slides/about/
⇒上記APIを使用すると、windowsで作成したパワポをインポートし、
　表示できる、かつ、アニメーションも表示できるかもしれません。

-----------------------------------

**Comment by fshin2000** [comment]
１．Ajaxによるファイルアップロード
https://qiita.com/yasumodev/items/516de8445d254ab12cbf

２．　DBに格納するスライド情報は画像情報(データURL)にすべきでしょうか？

いや、URLじゃなくていいです。サーバが移転した時とかにドメイン変わったりするし、将来Amazon S3とかに置くとURL構造が変わるので。（ファイル名本体は維持される）

3)スライドのアップロード方法について
＞・相談
＞　現手法（スライドを画像としてUL）だとアニメーション機能が使えません。
＞　この部分を解消してくれそうなAPI(Google Slides API)があり、気になっています。
＞　・アニメーションを再現する方法をもう少し探ってみるべきでしょうか？
＞　・まだミニマム要素（音声登録機能等の実装）が終わっていないので、
＞　　そちらを先に進めるべきでしょうか？

スライドのアニメーションの再現は難しいので、まずはミニマム要素を先に進めましょう。
サービス性が優れていればアニメーションなしでも大丈夫だし、その後で対応してもいいと思います。
slideshareとかはそもそもアニメーションに対応してなかった記憶が（今はどうだったかな）

スライドありきでサービス性が狭くなる可能性もあり、実現技術は別途研究して採用を検討すべきです。

Google Slide APIというのは、これっすね。Google presentationをいい感じに統合できれば、それはそれでありなのかもしれないと思いつつ、Googleは突如サービスが終わることで有名なので、そんなにヒットしてなさそうなpresentationに依存するのは微妙な印象もありつつ...。
https://qiita.com/howdy39/items/be30170f8722c6837ea5

**Comment by tsukamotomizuho** [comment]
コメントありがとうございます！

１．Ajaxによるファイルアップロード
⇒ありがとうございます！
　音声処理をやりつつ、こちらも試してみます。

２．DBに格納するスライド情報は画像情報(データURL)にすべきでしょうか？
⇒承知しました。
　ではとりあえず今の実装で(画像名のみDB保存)で実装を進めます。

3)スライドのアップロード方法について
⇒承知しました。
　まずはミニマム要素を先に進めますね！

>Googleは突如サービスが終わることで有名
⇒それは恐ろしすぎです。このあたりは一旦保留しますね。
　(またほかによさそうなものがないか、見繕っておくにとどめておきます。)
